on:
  pull_request:
    branches:
      -  master
      on: 
       schedule:
       - cron: "02**1-5"
jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    Strategy:
     matrix:
       node_version: ['10', '8', '12']
       os: [windows-latest, unbuntu-latest, macOS-latest]
       
    steps:
    - uses: actions/checkout@v1   
    - name: use node.js ${{ matrix.node_version }}
      uses: actions/setup-nodes@v1
      with:
        node-version: ${{ matrix.node_version }}
        
    - name: npm install, build and test
      run: |
        npm install 
        npm run build --if-present
        npm test           
  
    
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a one-line script
      run: echo Hello, world!
        echo Add other actions to build,
        echo test, and deploy your project.

          - release/*
